// import loading from '@vue/view/public/common/loading.vue';
import myAvatar from '@vue/view/public/common/my_avatar.vue';
import mySwitch from '@vue/view/public/common/my_switch.vue';
import myFullLoading from '@vue/view/public/common/my_full_loading.vue';
import myIcon from '@vue/view/public/common/my_icon.vue';
import myFormDrawer from '@vue/view/public/common/my_form_drawer.vue';
import myFormModal from '@vue/view/public/common/my_form_modal.vue';
import myDeepSelect from '@vue/view/public/common/my_deep_select.vue';
import mySelect from '@vue/view/public/common/my_select.vue';
import myTableButton from '@vue/view/public/common/my_table_button.vue';
import myLoading from '@vue/view/public/common/my_loading.vue';
import myPage from '@vue/view/public/common/my_page.vue';
import myTableImagePreview from '@vue/view/public/common/my_table_image_preview.vue';
import myTableImagePreviewByButton from '@vue/view/public/common/my_table_image_preview_by_button.vue';
import myTableVideoPreview from '@vue/view/public/common/my_table_video_preview.vue';
import myUserSelector from '@vue/view/public/core/selector/my_user_selector.vue';
import myImageSubjectSelector from '@vue/view/public/core/selector/my_image_subject_selector.vue';
import myCountrySelector from '@vue/view/public/core/selector/my_country_selector.vue';
import myVideoSeriesSelector from '@vue/view/public/core/selector/my_video_series_selector.vue';
import myVideoCompanySelector from '@vue/view/public/core/selector/my_video_company_selector.vue';
import myVideoProjectSelector from '@vue/view/public/core/selector/my_video_project_selector.vue';
import myBase from '@vue/view/public/common/my_base.vue';
import mySearchForm from '@vue/view/public/common/my_search_form.vue';
import mySearchFormItem from '@vue/view/public/common/my_search_form_item.vue';
import myVideoPreview from '@vue/view/public/common/my_video_preview.vue';
import myResourceSelector from '@vue/view/public/core/selector/my_resource_selector.vue';
import myImagePreview from '@vue/view/public/common/my_image_preview.vue';

Vue.component('my-base' , myBase);
// Vue.component('my-loading' , loading);
Vue.component('my-avatar' , myAvatar);
Vue.component('my-switch' , mySwitch);
Vue.component('my-full-loading' , myFullLoading);
Vue.component('my-deep-select' , myDeepSelect);
Vue.component('my-select' , mySelect);
Vue.component('my-form-drawer' , myFormDrawer);
Vue.component('my-form-modal' , myFormModal);
Vue.component('my-icon' , myIcon);
Vue.component('my-loading' , myLoading);
Vue.component('my-page' , myPage);
Vue.component('my-table-image-preview' , myTableImagePreview);
Vue.component('my-table-image-preview-by-button' , myTableImagePreviewByButton);
Vue.component('my-table-video-preview' , myTableVideoPreview);
Vue.component('my-table-button' , myTableButton);

Vue.component('my-user-selector' , myUserSelector);
Vue.component('my-image-subject-selector' , myImageSubjectSelector);
Vue.component('my-country-selector' , myCountrySelector);
Vue.component('my-video-series-selector' , myVideoSeriesSelector);
Vue.component('my-video-company-selector' , myVideoCompanySelector);
Vue.component('my-video-project-selector' , myVideoProjectSelector);
Vue.component('my-video-project-selector' , myVideoProjectSelector);
Vue.component('my-resource-selector' , myResourceSelector);

Vue.component('my-search-form' , mySearchForm);
Vue.component('my-search-form-item' , mySearchFormItem);
Vue.component('my-video-preview' , myVideoPreview);
Vue.component('my-image-preview' , myImagePreview);


